baseURL = "https://phoenixsun17.github.io/MIboxercise/"
languageCode = 'en-us'
title = 'MI-Boxercise Team 33'
theme = "ananke" 
[param]
  ananke_socials = true
  - name = linkedin
    url = https://www.linkedin.com/in/ruijun-sun-0b34ab1b7/
  - name = github
    url = https://github.com/PhoenixSun17
  - name = youtube
    url = https://www.youtube.com/channel/UCUDTis7KbnvtEKPhKIQ8I9w
